services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app


  cloudwatch-agent:
    image: amazon/cloudwatch-agent
    ports:
      - "2000:2000"
    environment:
      - AWS_REGION=us-west-2
    volumes:
      - ./cloudwatch-config.json:/etc/cwagentconfig/cloudwatch-config.json
      - ./volumes/syslog:/var/log/syslog
      - ./aws-credentials:/root/.aws/credentials
    command: ["-config", "/etc/cwagentconfig/cloudwatch-config.json"]
