[agent]
  collection_jitter = "0s"
  debug = true
  flush_interval = "1s"
  flush_jitter = "0s"
  hostname = ""
  interval = "5s"
  logfile = "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log"
  logtarget = "lumberjack"
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  omit_hostname = true
  precision = ""
  quiet = false
  round_interval = false

[inputs]

  [[inputs.logfile]]
    destination = "cloudwatchlogs"
    file_state_folder = "/opt/aws/amazon-cloudwatch-agent/logs/state"

    [[inputs.logfile.file_config]]
      file_path = "/var/log/fastapi.all.log/buffer.b61f1ca173bf102a4d4aebfa6d2e0a8d2.log"
      from_beginning = true
      log_group_class = ""
      log_group_name = "local-fastapi"
      log_stream_name = "local-fastapi-stream"
      pipe = false
      retention_in_days = -1
      timestamp_layout = ["2006-01-_2 15:04:05", "2006-1-_2 15:04:05"]
      timestamp_regex = "(\\d{4}-\\s{0,1}\\d{1,2}-\\s{0,1}\\d{1,2} \\d{2}:\\d{2}:\\d{2})"

[outputs]

  [[outputs.cloudwatchlogs]]
    force_flush_interval = "15s"
    log_stream_name = "3b116d1f88ab"
    mode = "OP"
    profile = "AmazonCloudWatchAgent"
    region = "us-west-2"
    region_type = "ACJ"
    shared_credential_file = "/root/.aws/credentials"
